<?php

namespace DoctrineORMModule\Proxy\__CG__\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Insumo extends \Entity\Insumo implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Entity\\Insumo' . "\0" . 'idInsumo', '' . "\0" . 'Entity\\Insumo' . "\0" . 'nome', '' . "\0" . 'Entity\\Insumo' . "\0" . 'codigo', '' . "\0" . 'Entity\\Insumo' . "\0" . 'unidadeMedida', '' . "\0" . 'Entity\\Insumo' . "\0" . 'alertaValorMinimo', '' . "\0" . 'Entity\\Insumo' . "\0" . 'estoqueGeral', '' . "\0" . 'Entity\\Insumo' . "\0" . 'valorMedio', '' . "\0" . 'Entity\\Insumo' . "\0" . 'observacao', '' . "\0" . 'Entity\\Insumo' . "\0" . 'ativo', '' . "\0" . 'Entity\\Insumo' . "\0" . 'dataCadastro', '' . "\0" . 'Entity\\Insumo' . "\0" . 'dataAtualizacao', '' . "\0" . 'Entity\\Insumo' . "\0" . 'dataRemocao'];
        }

        return ['__isInitialized__', '' . "\0" . 'Entity\\Insumo' . "\0" . 'idInsumo', '' . "\0" . 'Entity\\Insumo' . "\0" . 'nome', '' . "\0" . 'Entity\\Insumo' . "\0" . 'codigo', '' . "\0" . 'Entity\\Insumo' . "\0" . 'unidadeMedida', '' . "\0" . 'Entity\\Insumo' . "\0" . 'alertaValorMinimo', '' . "\0" . 'Entity\\Insumo' . "\0" . 'estoqueGeral', '' . "\0" . 'Entity\\Insumo' . "\0" . 'valorMedio', '' . "\0" . 'Entity\\Insumo' . "\0" . 'observacao', '' . "\0" . 'Entity\\Insumo' . "\0" . 'ativo', '' . "\0" . 'Entity\\Insumo' . "\0" . 'dataCadastro', '' . "\0" . 'Entity\\Insumo' . "\0" . 'dataAtualizacao', '' . "\0" . 'Entity\\Insumo' . "\0" . 'dataRemocao'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Insumo $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdInsumo()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdInsumo();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdInsumo', []);

        return parent::getIdInsumo();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdInsumo($idInsumo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdInsumo', [$idInsumo]);

        return parent::setIdInsumo($idInsumo);
    }

    /**
     * {@inheritDoc}
     */
    public function getNome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNome', []);

        return parent::getNome();
    }

    /**
     * {@inheritDoc}
     */
    public function setNome($nome)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNome', [$nome]);

        return parent::setNome($nome);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodigo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodigo', []);

        return parent::getCodigo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodigo($codigo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodigo', [$codigo]);

        return parent::setCodigo($codigo);
    }

    /**
     * {@inheritDoc}
     */
    public function getUnidadeMedida()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUnidadeMedida', []);

        return parent::getUnidadeMedida();
    }

    /**
     * {@inheritDoc}
     */
    public function setUnidadeMedida($unidadeMedida)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUnidadeMedida', [$unidadeMedida]);

        return parent::setUnidadeMedida($unidadeMedida);
    }

    /**
     * {@inheritDoc}
     */
    public function getAlertaValorMinimo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlertaValorMinimo', []);

        return parent::getAlertaValorMinimo();
    }

    /**
     * {@inheritDoc}
     */
    public function setAlertaValorMinimo($alertaValorMinimo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAlertaValorMinimo', [$alertaValorMinimo]);

        return parent::setAlertaValorMinimo($alertaValorMinimo);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstoqueGeral()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstoqueGeral', []);

        return parent::getEstoqueGeral();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstoqueGeral($estoqueGeral)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstoqueGeral', [$estoqueGeral]);

        return parent::setEstoqueGeral($estoqueGeral);
    }

    /**
     * {@inheritDoc}
     */
    public function getValorMedio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValorMedio', []);

        return parent::getValorMedio();
    }

    /**
     * {@inheritDoc}
     */
    public function setValorMedio($valorMedio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValorMedio', [$valorMedio]);

        return parent::setValorMedio($valorMedio);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservacao', []);

        return parent::getObservacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservacao($observacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservacao', [$observacao]);

        return parent::setObservacao($observacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getAtivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAtivo', []);

        return parent::getAtivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setAtivo($ativo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAtivo', [$ativo]);

        return parent::setAtivo($ativo);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataCadastro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataCadastro', []);

        return parent::getDataCadastro();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataCadastro($dataCadastro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataCadastro', [$dataCadastro]);

        return parent::setDataCadastro($dataCadastro);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataAtualizacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataAtualizacao', []);

        return parent::getDataAtualizacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataAtualizacao($dataAtualizacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataAtualizacao', [$dataAtualizacao]);

        return parent::setDataAtualizacao($dataAtualizacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataRemocao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataRemocao', []);

        return parent::getDataRemocao();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataRemocao($dataRemocao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataRemocao', [$dataRemocao]);

        return parent::setDataRemocao($dataRemocao);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', []);

        return parent::toArray();
    }

    /**
     * {@inheritDoc}
     */
    public function getArrayCopy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArrayCopy', []);

        return parent::getArrayCopy();
    }

}
