<nav class="navbar navbar-top navbar-expand-md navbar-dark" id="navbar-main">
    <div class="container-fluid">
        <a class="h4 mb-0 text-white text-uppercase d-none d-lg-inline-block" href="<?= $this->url('ProdutoLista') ?>">Produto</a>
    </div>
</nav>
<div class="header bg-gradient-primary pb-5 pt-6 pt-md-0">
</div>
<div class="main-content">
    <div class="container-fluid">
        <div class="">
            <div class="row mt-5">
                <div class="col-xl-12 mb-5 mb-xl-0">

                    <?php if ($this->msgs): ?>
                        <div class="alert alert-success" role="alert">
                            <strong>Sucesso!</strong> <?= $this->msgs; ?>
                        </div>
                    <?php endif; ?>
                    <?php if ($this->msge): ?>
                        <div class="alert alert-danger" role="alert">
                            <strong>Erro!</strong> <?= $this->msge; ?>
                        </div>
                    <?php endif; ?>

                    <div class="card shadow">
                        <div class="card-header border-0">
                            <div class="row align-items-center">
                                <div class="col col-md-12">
                                    <h3 class="mb-0"><span class="fa fa-box"></span> Editar Produto</h3>
                                </div>
                            </div>
                            <div class="row align-items-center">
                                <div class="col col-md-12">
                                    <form action="" method="post">
                                        <input type="hidden" name="idproduto"
                                               value="<?= $this->produto->getIdProduto(); ?>">
                                        <div class="p-2">
                                            Código do produto <span class="text-red">*</span>
                                            <div class="form-group">
                                                <input required maxlength="15" type="text" class="form-control"
                                                       id="codigo" name="codigo" placeholder="Ex: 0001"
                                                       value="<?= $this->produto->getCodigo() ?>">
                                            </div>
                                            Nome do produto <span class="text-red">*</span>
                                            <div class="form-group">
                                                <input required maxlength="100" type="text" class="form-control"
                                                       name="nome" id="nome" placeholder="Ex: Produto x"
                                                       value="<?= $this->produto->getNome() ?>">
                                            </div>
                                            <span data-toggle="tooltip" data-placement="top"
                                                  title="A unidade de medida reflete diretamente na fabricação do produto.">Unidade de medida</span>
                                            <span class="text-red">*</span> <span class="ni ni-tag text-red"
                                                                                  data-toggle="tooltip"
                                                                                  data-placement="top"
                                                                                  title="A unidade de medida reflete diretamente na fabricação do produto."></span>
                                            <div class="form-group">
                                                <select name="unidade_medida" id="unidade_medida" class="form-control"
                                                        required>
                                                    <option></option>
                                                    <optgroup label="Pesos">
                                                        <option value="T" <?php if ($this->produto->getUnidadeMedida() == 'T'): ?> selected <?php endif; ?>>
                                                            TONELADA
                                                        </option>
                                                        <option value="KG" <?php if ($this->produto->getUnidadeMedida() == 'KG'): ?> selected <?php endif; ?>>
                                                            QUILOGRAMA
                                                        </option>
                                                        <option value="G" <?php if ($this->produto->getUnidadeMedida() == 'G'): ?> selected <?php endif; ?>>
                                                            GRAMA
                                                        </option>
                                                        <option value="MG" <?php if ($this->produto->getUnidadeMedida() == 'MG'): ?> selected <?php endif; ?>>
                                                            MILIGRAMA
                                                        </option>
                                                    </optgroup>
                                                    <optgroup label="Líquidos">
                                                        <option value="L" <?php if ($this->produto->getUnidadeMedida() == 'L'): ?> selected <?php endif; ?>>
                                                            LITRO
                                                        </option>
                                                        <option value="ML" <?php if ($this->produto->getUnidadeMedida() == 'ML'): ?> selected <?php endif; ?>>
                                                            MILILITRO
                                                        </option>
                                                    </optgroup>
                                                </select>
                                            </div>
                                            Descrição
                                            <div class="form-group">
                                                <textarea name="descricao" id="descricao" class="form-control" rows="3"
                                                          placeholder="Descrição do Produto"><?= $this->produto->getDescricao() ?></textarea>
                                            </div>

                                            <div class="card shadow">
                                                <div class="card-header border-0">
                                                    <div class="row align-items-center">
                                                        <div class="col col-md-12">
                                                            <h3 class="mb-0"><span class="fa fa-database"></span>
                                                                Composição do Produto</h3>
                                                        </div>
                                                    </div>
                                                    <div class="row align-items-center">
                                                        <div class="col col-md-12">
                                                            <div class="table-responsive">
                                                                <!-- Projects table -->
                                                                <table id="example"
                                                                       class="dataTable table align-items-cente">
                                                                    <thead>
                                                                    <tr>
                                                                        <th class="text-center">Código</th>
                                                                        <th>Nome</th>
                                                                        <th>Quantidade</th>
                                                                        <th class="text-center">Unidade de Medida</th>
                                                                        <th class="text-center">Ação</th>
                                                                    </tr>
                                                                    </thead>
                                                                    <tbody>
                                                                    <?php foreach ($this->insumos as $insumo): ?>
                                                                        <tr>
                                                                            <td class="text-center">
                                                                                <strong>
                                                                                    <div id="codigo<?= $insumo->getIdInsumo() ?>"><?= $insumo->getCodigo() ?></div>
                                                                                </strong>
                                                                            </td>
                                                                            <td>
                                                                                <div id="nome<?= $insumo->getIdInsumo() ?>"><?= $insumo->getNome() ?></div>
                                                                            </td>
                                                                            <td class="text-center">
                                                                                <input maxlength="15"
                                                                                       type="text"
                                                                                       class="form-control form-control-sm decimal"
                                                                                       id="quantidade<?= $insumo->getIdInsumo() ?>"
                                                                                       name="quantidade"
                                                                                       placeholder="Ex: 1">
                                                                            </td>
                                                                            <td class="text-center">
                                                                                <div id="unidade<?= $insumo->getIdInsumo() ?>"><?= $insumo->getUnidadeMedida() ?></div>
                                                                            </td>
                                                                            <td class="text-center">
                                                                                <button type="button"
                                                                                        onclick="addFormula(<?= $insumo->getIdInsumo() ?>)"
                                                                                        class="btn btn-info btn-sm"><span
                                                                                            class="fa fa-plus"></span>
                                                                                    Adicionar
                                                                                </button>
                                                                            </td>
                                                                        </tr>
                                                                    <?php endforeach; ?>
                                                                    </tbody>
                                                                </table>
                                                            </div>

                                                            <h4><span class="fa fa-list"></span> Insumos adicionados a
                                                                composição</h4>
                                                            <div class="table-responsive">
                                                                <!-- Projects table -->
                                                                <table id="formula"
                                                                       class="table align-items-cente">
                                                                    <thead>
                                                                    <tr>
                                                                        <th>Código</th>
                                                                        <th>Nome</th>
                                                                        <th class="text-center">Quantidade</th>
                                                                        <th class="text-center">Unidade de Medida</th>
                                                                        <th class="text-center">Ação</th>
                                                                    </tr>
                                                                    </thead>
                                                                    <tbody>
                                                                    <?php if (count($this->composicao) == 0): ?>
                                                                        <tr id="default">
                                                                            <td colspan="5" class="text-center"> Nenhum
                                                                                registro encontrado!
                                                                            </td>
                                                                        </tr>
                                                                    <?php else: ?>
                                                                        <?php foreach ($this->composicao as $comp): ?>
                                                                            <tr class='composicao'
                                                                                id='comp<?= $comp->getInsumo()->getIdInsumo();?>'>
                                                                                <td>
                                                                                    <input type='hidden' name='insumo[]' value='<?= $comp->getInsumo()->getIdInsumo();?>'>
                                                                                    <input type='hidden' name='quantidade[<?= $comp->getInsumo()->getIdInsumo();?>]' value='<?= $comp->getQtde();?>'>
                                                                                    <?= $comp->getInsumo()->getCodigo();?>
                                                                                </td>
                                                                                <td>
                                                                                    <?= $comp->getInsumo()->getNome();?>
                                                                                </td>
                                                                                <td class="text-center">
                                                                                    <?= $comp->getQtde();?>
                                                                                </td>
                                                                                <td class="text-center">
                                                                                    <?= $comp->getInsumo()->getUnidadeMedida();?>
                                                                                </td>
                                                                                <td class="text-center">
                                                                                    <button type="submit" class="btn btn-danger btn-sm" onclick="removerLinha(<?= $comp->getInsumo()->getIdInsumo();?>)"><span class="fa fa-window-close"></span> Remover</button>
                                                                                </td>
                                                                            </tr>
                                                                        <?php endforeach; ?>
                                                                    <?php endif; ?>
                                                                    </tbody>
                                                                </table>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <p></p>
                                            <div class="form-group">
                                                <button type="submit" class="btn btn-success"><span
                                                            class="fa fa-save"></span> Editar
                                                </button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('.decimal').mask('000000000000000.00', {reverse: true});
    });
</script>

<script src="<?= $this->basePath('public/js/formula.js'); ?>"></script>