<nav class="navbar navbar-top navbar-expand-md navbar-dark" id="navbar-main">
    <div class="container-fluid">
        <a class="h4 mb-0 text-white text-uppercase d-none d-lg-inline-block" href="./index.html">Inicial</a>
    </div>
</nav>
<div class="header bg-gradient-primary pb-8 pt-3 pt-md-6">
    <div class="container-fluid">
        <div class="header-body">
            <!-- Card stats -->
            <div class="row">
                <div class="col-xl-3 col-lg-6">
                    <div class="card card-stats mb-4 mb-xl-0">
                        <div class="card-body">
                            <div class="row">
                                <div class="col">
                                    <h5 class="card-title text-uppercase text-muted mb-0">Insumos</h5>
                                    <span class="h2 font-weight-bold mb-0"><?= 'R$ ' . number_format($this->compraInsumo['valor'], 2, '.', '') ?></span>
                                </div>
                                <div class="col-auto">
                                    <div class="icon icon-shape bg-danger text-white rounded-circle shadow">
                                        <i class="ni ni-palette"></i>
                                    </div>
                                </div>
                            </div>
                            <p class="mt-3 mb-0 text-muted text-sm">
                                <span class="mr-2"><i class="fa <?php if($this->compraInsumo['tik'] == 'up'):?>text-success fa-arrow-up<?php else:?>text-danger fa-arrow-down<?php endif;?>"></i> <?= $this->compraInsumo['porcentagem']?>%</span>
                                <span class="text-nowrap">Último Mês</span>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-lg-6">
                    <div class="card card-stats mb-4 mb-xl-0">
                        <div class="card-body">
                            <div class="row">
                                <div class="col">
                                    <h5 class="card-title text-uppercase text-muted mb-0">Fabricação</h5>
                                    <span class="h2 font-weight-bold mb-0"><?= $this->fabricacaoMes['valor']; ?></span>
                                </div>
                                <div class="col-auto">
                                    <div class="icon icon-shape bg-warning text-white rounded-circle shadow">
                                        <i class="ni ni-spaceship"></i>
                                    </div>
                                </div>
                            </div>
                            <p class="mt-3 mb-0 text-muted text-sm">
                                <span class="mr-2"><i class="fas <?php if($this->fabricacaoMes['tik'] == 'up'):?>text-success fa-arrow-up<?php else:?> text-danger fa-arrow-down<?php endif;?>"></i> <?= $this->fabricacaoMes['porcentagem']?>%</span>
                                <span class="text-nowrap">Último Mês</span>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-lg-6">
                    <div class="card card-stats mb-4 mb-xl-0">
                        <div class="card-body">
                            <div class="row">
                                <div class="col">
                                    <h5 class="card-title text-uppercase text-muted mb-0">Produtos</h5>
                                    <span class="h2 font-weight-bold mb-0"><?= $this->totalProduto;?></span>
                                </div>
                                <div class="col-auto">
                                    <div class="icon icon-shape bg-yellow text-white rounded-circle shadow">
                                        <i class="fas fa-box"></i>
                                    </div>
                                </div>
                            </div>
                            <div style="height: 40px;"></div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-lg-6">
                    <div class="card card-stats mb-4 mb-xl-0">
                        <div class="card-body">
                            <div class="row">
                                <div class="col">
                                    <h5 class="card-title text-uppercase text-muted mb-0">Estoque</h5>
                                    <span class="h2 font-weight-bold mb-0"><?= $this->estoqueGeral?></span>
                                </div>
                                <div class="col-auto">
                                    <div class="icon icon-shape bg-info text-white rounded-circle shadow">
                                        <i class="ni ni-spaceship"></i>
                                    </div>
                                </div>
                            </div>
                            <div style="height: 40px;"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid mt--7">
    <div class="row">
        <div class="col-xl-8 mb-5 mb-xl-0">
            <div class="card bg-gradient-default shadow">
                <div class="card-header bg-transparent">
                    <div class="row align-items-center">
                        <div class="col">
                            <h6 class="text-uppercase text-light ls-1 mb-1">Produto</h6>
                            <h2 class="text-white mb-0">Fabricação</h2>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <!-- Chart -->
                    <div class="chart">
                        <!-- Chart wrapper -->
                        <canvas id="chart-sales" class="chart-canvas"></canvas>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xl-4">
            <div class="card shadow">
                <div class="card-header bg-transparent">
                    <div class="row align-items-center">
                        <div class="col">
                            <h6 class="text-uppercase text-muted ls-1 mb-1">Produto</h6>
                            <h2 class="mb-0">Compra de Insumos</h2>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <!-- Chart -->
                    <div class="chart">
                        <canvas id="chart-orders" class="chart-canvas"></canvas>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row mt-5">
        <div class="col-xl-12 mb-5 mb-xl-0">
            <div class="card shadow">
                <div class="card-header border-0">
                    <div class="row align-items-center">
                        <div class="col">
                            <h3 class="mb-0">Estoque de Produtos Fabricados</h3>
                        </div>
                    </div>
                </div>
                <div class="table-responsive">
                    <!-- Projects table -->
                    <table class="table align-items-center table-flush">
                        <thead class="thead-light">
                        <tr>
                            <th scope="col">Produto</th>
                            <th scope="col" class="text-center">Total Estoque Produzido</th>
                            <th scope="col" class="text-center">Valor Médio</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($this->estoqueProduto as $estoque):?>
                            <tr>
                                <th scope="row">
                                    <?= $estoque['nome'];?>
                                </th>
                                <td class="text-center">
                                    <?= $estoque['totalEstoque'];?>
                                </td>
                                <td class="text-center">
                                    <?= 'R$ ' . number_format(($estoque['valor']/$estoque['totalEstoque']), 2, '.', '') ?>
                                </td>
                            </tr>
                        <?php endforeach;?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <script>

        <?php
            $moth = [
                '01' => 'Jan',
                '02' => 'Fev',
                '03' => 'Mar',
                '04' => 'Abr',
                '05' => 'Mai',
                '06' => 'Jun',
                '07' => 'Jul',
                '08' => 'Ago',
                '09' => 'Set',
                '10' => 'Out',
                '11' => 'Nov',
                '12' => 'Dez',
            ];
        ?>
        //
        // Sales chart
        //

        var SalesChart = (function() {

            // Variables

            var $chart = $('#chart-sales');


            // Methods

            function init($chart) {

                var salesChart = new Chart($chart, {
                    type: 'line',
                    options: {
                        scales: {
                            yAxes: [{
                                gridLines: {
                                    lineWidth: 1,
                                    color: Charts.colors.gray[900],
                                    zeroLineColor: Charts.colors.gray[900]
                                },
                                ticks: {
                                    callback: function(value) {
                                        if (!(value % 10)) {
                                            return  value ;
                                        }
                                    }
                                }
                            }]
                        },
                        tooltips: {
                            callbacks: {
                                label: function(item, data) {
                                    var label = data.datasets[item.datasetIndex].label || '';
                                    var yLabel = item.yLabel;
                                    var content = '';

                                    if (data.datasets.length > 1) {
                                        content += '<span class="popover-body-label mr-auto">' + label + '</span>';
                                    }

                                    content += '<span class="popover-body-value">' + yLabel + '</span>';
                                    return content;
                                }
                            }
                        }
                    },
                    data: {
                        labels: [<?php $tot = 0; foreach ($this->gFabricacao as $mes => $valor): $tot++;?>'<?= $moth[$mes];?>'<?php if($tot < count($this->gFabricacao)){echo ',';}?><?php endforeach;?>],
                        datasets: [{
                            label: 'Performance',
                            data: [<?php $tot = 0; foreach ($this->gFabricacao as $mes => $valor): $tot++;?><?= $valor;?><?php if($tot < count($this->gFabricacao)){echo ',';}?><?php endforeach;?>]
                        }]
                    }
                });

                // Save to jQuery object

                $chart.data('chart', salesChart);

            };


            // Events

            if ($chart.length) {
                init($chart);
            }

        })();
    </script>

    <script>
        var OrdersChart = (function() {

            //
            // Variables
            //

            var $chart = $('#chart-orders');
            var $ordersSelect = $('[name="ordersSelect"]');


            //
            // Methods
            //

            // Init chart
            function initChart($chart) {

                // Create chart
                var ordersChart = new Chart($chart, {
                    type: 'bar',
                    options: {
                        scales: {
                            yAxes: [{
                                gridLines: {
                                    lineWidth: 1,
                                    color: '#dfe2e6',
                                    zeroLineColor: '#dfe2e6'
                                },
                                ticks: {
                                    callback: function(value) {
                                        if (!(value % 10)) {
                                            //return '$' + value + 'k'
                                            return value
                                        }
                                    }
                                }
                            }]
                        },
                        tooltips: {
                            callbacks: {
                                label: function(item, data) {
                                    var label = data.datasets[item.datasetIndex].label || '';
                                    var yLabel = item.yLabel;
                                    var content = '';

                                    if (data.datasets.length > 1) {
                                        content += '<span class="popover-body-label mr-auto">R$ ' + label + '</span>';
                                    }

                                    content += '<span class="popover-body-value">R$' + yLabel + '</span>';

                                    return content;
                                }
                            }
                        }
                    },
                    data: {
                        labels: [<?php $tot = 0; foreach ($this->gInsumo as $mes => $valor): $tot++;?>'<?= $moth[$mes];?>'<?php if($tot < count($this->gFabricacao)){echo ',';}?><?php endforeach;?>],
                        datasets: [{
                            label: 'Sales',
                            data: [<?php $tot = 0; foreach ($this->gInsumo as $mes => $valor): $tot++;?>'<?= $valor;?>'<?php if($tot < count($this->gFabricacao)){echo ',';}?><?php endforeach;?>]
                        }]
                    }
                });

                // Save to jQuery object
                $chart.data('chart', ordersChart);
            }


            // Init chart
            if ($chart.length) {
                initChart($chart);
            }

        })();
    </script>