<nav class="navbar navbar-top navbar-expand-md navbar-dark" id="navbar-main">
    <div class="container-fluid">
        <a class="h4 mb-0 text-white text-uppercase d-none d-lg-inline-block" href="<?= $this->url('ProdutoLista') ?>">Produto</a>
    </div>
</nav>
<div class="header bg-gradient-primary pb-5 pt-6 pt-md-0">
</div>
<div class="main-content">
    <div class="container-fluid">
        <div class="">
            <div class="row mt-5">
                <div class="col-xl-12 mb-5 mb-xl-0">

                    <?php if ($this->msgs): ?>
                        <div class="alert alert-success" role="alert">
                            <strong>Sucesso!</strong> <?= $this->msgs; ?>
                        </div>
                    <?php endif; ?>
                    <?php if ($this->msge): ?>
                        <div class="alert alert-danger" role="alert">
                            <strong>Erro!</strong> <?= $this->msge; ?>
                        </div>
                    <?php endif; ?>

                    <div class="card shadow">
                        <div class="card-header border-0">
                            <div class="row align-items-center">
                                <div class="col col-md-12">
                                    <h3 class="mb-0"><span class="fa fa-box"></span> Cadastro de Produto</h3>
                                </div>
                            </div>
                            <div class="row align-items-center">
                                <div class="col col-md-12">
                                    <form action="" method="post">
                                        <div class="p-2">
                                            Produto a ser fabricado <span class="text-red">*</span>
                                            <div class="form-group">
                                                <select name="produto" id="produto" class="form-control"
                                                        required>
                                                    <option></option>
                                                    <?php foreach ($this->produtos as $produto):?>
                                                        <option value="<?= $produto->getIdProduto();?>"><?= $produto->getNome();?></option>
                                                    <?php endforeach;?>
                                                </select>
                                            </div>
                                            Quantidade a ser fabricada <span class="text-red">*</span>
                                            <div class="form-group">
                                                <input required type="text" class="form-control decimal"
                                                       id="quantidade" name="quantidade" placeholder="Ex: 10.5" onkeyup="carregaInfoFabricacao()">
                                            </div>
                                            Descrição
                                            <div class="form-group">
                                                <textarea name="descricao" id="descricao" class="form-control" rows="3"
                                                          placeholder="Descrição do Produto"></textarea>
                                            </div>
                                            <div id="infofabricacao"></div>
                                            <p> </p>
                                            <div class="form-group">
                                                <button id="botaoH" type="submit" class="btn btn-success" disabled><span
                                                            class="fa fa-plus"></span> Cadastrar
                                                </button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('.decimal').mask('000000000000000.00', {reverse: true});
    });
</script>

<script src="<?= $this->basePath('public/js/formula.js');?>"></script>

<script>
    function carregaInfoFabricacao() {
        var idProduto = $('#produto').val();
        var qtde = $('#quantidade').val();
        if (idProduto && qtde) {
            $('#infofabricacao').html('Carregando informações...');
            $('#infofabricacao').load('../info/' + idProduto + '/' + qtde );
        }
    }

    function botao(habilita) {
        if(habilita) {
            $('#botaoH').attr('disabled', false);
            return;
        }

        $('#botaoH').attr('disabled', true);
    }
</script>